config/routes.rb
Rails.application.routes.draw do
  resources :event_images

  mount Ckeditor::Engine => '/ckeditor'
  resources :user_profiles

  resources :locations

  resources :exercises

  resources :event_times

  resources :events
  
  resources :user_event_times

  devise_for :users

  root 'event_times#index'

end

app/models/event_time.rb
class EventTime < ActiveRecord::Base
  belongs_to :event, :foreign_key => "event_id"
  has_many :location_events
  has_many :locations, through: :location_events
  has_many :event_time_images
  has_many :event_images, through: :event_time_images
  has_many :exercise_events, :dependent => :destroy
  has_many :exercises, through: :exercise_events
  has_many :user_event_times
  has_many :users, through: :user_event_times
  
  accepts_nested_attributes_for :event
  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :exercise_events,:reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
end

app/controllers/event_times_controller.rb
class EventTimesController < ApplicationController
  before_action :set_event_time, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    #get this weeks date or the date required
    if params.has_key?(:start_date)
      begin
        start_date = Date.parse(params[:start_date])
        
      rescue ArgumentError
        start_date=Date.current()
        
      end 
    else  
      start_date=Date.current()
    end
    start_date = start_date.beginning_of_week()
    #get last date
    end_date=start_date.to_time.advance(:weeks => 1).to_date
    @end_date=end_date
    #get previous date
    previous_date=start_date.to_time.advance(:weeks => -1).to_date
    @previous_date=previous_date
    #get first date from db and check if next tabs available
    first_record=EventTime.order('start_time DESC').last
    first_date=first_record.start_time.to_date
    if previous_date>=first_date
      @previous_link=0
    else
      @previous_link=1
    end
    #get last date from db and check if next tab is available
    last_record=EventTime.order('start_time DESC').first
    final_date=last_record.start_time.to_date
    if end_date<=final_date
      
      @next_link=0
    else
      @next_link=1
    end
    @start_date=start_date
    @event_times = EventTime.where(:start_time => start_date...end_date).order('start_time')
    @event_days = @event_times.group_by{|day| day.start_time.beginning_of_day}
    puts @event_days
    respond_with(@event_times)
  end

  def show
    respond_with(@event_time)
  end

  def new
    @event_time = EventTime.new
    respond_with(@event_time)
  end

  def edit
  end

  def create
    
    #get the parameters
    new_event_params=event_time_params
    
    #manipulate the dates for db storage
    new_event_params[:start_time] = DateTime.strptime(new_event_params[:start_time],'%m/%d/%Y %I:%M %p')
    new_event_params[:end_time] = DateTime.strptime(new_event_params[:end_time],'%m/%d/%Y %I:%M %p')
    
    #create new event
    @event_time = EventTime.new(new_event_params)
    
    #create new exercises if they exist
    if new_event_params[:exercise_events_attributes]..present?
      new_event_params[:exercise_events_attributes].each do |exercise|
        @event_time.exercise_events.build(:exercise_id => exercise[1][:exercise_id])
      end
    end
    
    #save the event
    @event_time.save
    
    respond_with(@event_time)
  end

  def update
    @event_time.update(event_time_params)
    respond_with(@event_time)
  end

  def destroy
    @event_time.destroy
    respond_with(@event_time)
  end

  private
    def set_event_time
      @event_time = EventTime.find(params[:id])
    end

    def event_time_params
      params.require(:event_time).permit(:start_time, :end_time, :max_participants,:event_id, exercise_events_attributes: [ :exercise_id,:_destroy])
    end
end

app/helpers/event_times_helper.rb
module EventTimesHelper
end

app/views/event_times/_form.html.slim
ul.errors
= simple_nested_form_for(@event_time) do |f|
  = f.error_notification
  .form-inputs
    .events
     .row  
       .form-group
         = f.label 'Class', class: "col-sm-2 control-label"
         .col-sm-6
           = f.collection_select :event_id, Event.all, :id, :name,{}, {class: "selectpicker" }
           javascript:
             $('.selectpicker').selectpicker('refresh');
           = link_to "New Event", new_event_path , remote:true ,  data: { toggle: "modal", target: "#ajax-modal" }, class:"btn btn-default"
           #event_description
     .row
      .form-group
        = f.label 'Class Image', class: "col-sm-2 control-label"
        .col-sm-6
          = f.simple_fields_for :exercise_time_image do |eti|
           = eti.select :event_id,options_from_collection_for_select_with_attributes(EventImage.all, 'id', 'alt_text', 'data-img-src', 'event_image',  :id)
           javascript:
            $("select").imagepicker()
             
           = link_to "New Image", new_event_image_path , remote:true ,  data: { toggle: "modal", target: "#ajax-modal" }, class:"btn btn-default"
    .row
      .form-group
          = f.label :start_time, class: "col-sm-2 control-label"
          .col-sm-6
            = f.input_field :start_time, as: :date_time_picker
    .row
      .form-group
          = f.label :end_time, class: "col-sm-2 control-label"
          .col-sm-6
            = f.input_field :end_time, as: :date_time_picker, class: "form-control"
    .row
      .form-group
          = f.label :max_participants, class: "col-sm-2 control-label"
          .col-sm-6
            = f.input_field :max_participants, class: "form-control bfh-number" , min: '0'
    .row
      .form-group
        .col-sm-2
        .col-sm-6
          = f.simple_fields_for :exercise_events do |et|
           = et.collection_select :exercise_id, Exercise.all, :id, :name,{}, {class: "selectpicker exercise_list"}
           = link_to "New Exercise", new_exercise_path , remote:true ,  data: { toggle: "modal", target: "#ajax-modal" }, class:"btn btn-default"
           = et.link_to_remove "Remove Exercise", class:"btn btn-default"
           javascript:
             $('.selectpicker').selectpicker('refresh');
          = f.link_to_add "Add Exercise", :exercise_events, class:"btn btn-default"
    .row
      .form-actions
        .col-sm-offset-2.col-sm-6
          = f.button :submit, 'Create'

app/views/event_times/edit.html.slim
h1 Editing event_time

== render 'form'

= link_to 'Show', @event_time
'|
= link_to 'Back', event_times_path

app/views/event_times/index.html.slim
h3 = 'Classes for week beginning ' + @start_date.strftime("%A #{@start_date.day.ordinalize} %B %Y")
- @event_days.each do |event_day|
  .panel.panel-default
    .panel-heading
      .event_day
        h3 = event_day[0].strftime("%A #{event_day[0].day.ordinalize} of %B")
    - event_day[1].each do |event_time|
      .event_container
        .panel.panel-default
          .panel-heading
            h4 = event_time.event.name
          .event_image  
          .event_details
             ul
               li ="Start Time: " + event_time.start_time.strftime("%l:%M %p")
               li ="End Time: " + event_time.end_time.strftime("%l:%M %p")
               li ="Places: " + (event_time.max_participants - event_time.user_event_times.count).to_s
               - if event_time.user_event_times.where(user_id: current_user.id).count ==0  
                 - if event_time.max_participants > event_time.user_event_times.where(user_id: current_user.id).count
                   li = simple_form_for(UserEventTime.new) do |f|
                        = f.hidden_field :event_time_id, :value => event_time.id
                        = f.button :submit, 'Join Class', class: "btn btn-info"
                 - else
                   li = simple_form_for(UserEventTime.new) do |f|
                        = f.hidden_field :event_time_id, :value => event_time.id
                        = f.button :submit, 'Full Class', class: "btn btn-info"    
               - else  
                 li = link_to 'Leave Class',user_event_time_path(id: event_time.user_event_times.where(user_id: current_user.id).first), data: {:confirm => 'Lazy Bones!'}, :method => :delete,class: "btn btn-success"
        
          .event_management
            ul
              - event_time.user_event_times.each do |attendee|
                li = attendee.id
            .edit_event = link_to 'Edit', edit_event_time_path(event_time),class: "btn btn-primary" 
          .panel-footer.clearfix 
             .show_event.pull-right = link_to 'Show', event_time,class: "btn btn-primary" 
.event_pagination 
  - if @previous_link == 0
    .previous_link =  link_to '< Previous week',event_times_path(:start_date => @previous_date),class: "btn btn-success"
  - else  
    .previous_link = ''
  - if @next_link == 0
    .next_link =  link_to 'Next week >>',event_times_path(:start_date => @end_date),class: "btn btn-success"
  - else  
    .next_link = ''
= link_to 'New Event time', new_event_time_path

app/views/event_times/new.html.slim
h3 Create Event
#event_form
  == render 'form'

= link_to 'Back', event_times_path

app/views/event_times/show.html.slim
.container
  p#notice = notice  
  h3= @event_time.event.name
  .row
    h4= "Start time:"
    = @event_time.start_time.to_formatted_s(:long)
  .row
    h4= "End time:"
    = @event_time.end_time.to_formatted_s(:long)
  .row
    h4= "Max participants:"
    = @event_time.max_participants
  .row
    h4= "Description:"
    row
    = @event_time.event.description
  .row
    h4= "Exercises:"
    - @event_time.exercises.each do |exercise|
      .row
      = exercise.name
      

  
  = link_to 'Edit', edit_event_time_path(@event_time)
  '|
  = link_to 'Back', event_times_path