config/routes.rb
Rails.application.routes.draw do
  resources :event_images

  mount Ckeditor::Engine => '/ckeditor'
  resources :user_profiles

  resources :locations

  resources :exercises

  resources :event_times

  resources :events
  
  resources :user_event_times

  devise_for :users

  root 'event_times#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
        user ||= User.new # guest user (not logged in)
        if user.admin?
          can :manage, :all
        else
          can :read, :all
        end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_times
  validates_presence_of :name,:description
end

app/models/event_image.rb
class EventImage < ActiveRecord::Base
  has_attached_file :event_image_thumb, :styles => { }, :default_url => "/images/:style/missing.png"
  has_attached_file :event_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :event_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :event_image_thumb, :content_type => /\Aimage\/.*\Z/
  has_many :event_times, through: :event_time_images
end

app/models/event_time.rb
class EventTime < ActiveRecord::Base
  belongs_to :event, :foreign_key => "event_id"
  has_many :location_events
  has_many :locations, through: :location_events
  has_many :event_time_images
  has_many :event_images, through: :event_time_images
  has_many :exercise_events, :dependent => :destroy
  has_many :exercises, through: :exercise_events
  has_many :user_event_times
  has_many :users, through: :user_event_times
  
  accepts_nested_attributes_for :event
  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :exercise_events,:reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
end

app/models/event_time_image.rb
class EventTimeImage < ActiveRecord::Base
  belongs_to :event_time
  belongs_to :event_images
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :exercise_events
  has_many :event_times, through: :excercise_events
end

app/models/exercise_event.rb
class ExerciseEvent < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :event_time
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :location_events
  has_many :event_times ,through: :location_events
end

app/models/location_event.rb
class LocationEvent < ActiveRecord::Base
  belongs_to :locations
  belongs_to :event_times
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :user_event_times
  has_many :event_times, through: :user_event_times
end

app/models/user_event_time.rb
class UserEventTime < ActiveRecord::Base
  belongs_to :users
  belongs_to :event_time
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    
    @event = Event.new
    respond_to do |format|
      format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
      format.js
    end
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
    #passed  
    else
    #errors
    @event.errors.full_messages
   
    end
    respond_to do |format|
        format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
        format.js
      end  
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description)
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  
  def index
    @exercises = Exercise.all
    respond_with(@exercises)
  end

  def show
    respond_with(@exercise)
  end

  def new
    @exercise = Exercise.new
    respond_to do |format|
      format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
      format.js
    end
  end

  def edit
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
    #passed  
    else
    #errors
    @exercise.errors.full_messages
   
    end
    respond_to do |format|
        format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
        format.js
      end  
  end

  def update
    @exercise.update(exercise_params)
    respond_with(@exercise)
  end

  def destroy
    @exercise.destroy
    respond_with(@exercise)
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:name, :description)
    end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    @user_profiles = UserProfile.all
    respond_with(@user_profiles)
  end

  def show
    respond_with(@user_profile)
  end

  def new
    @user_profile = UserProfile.new
    respond_with(@user_profile)
  end

  def edit
  end

  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.save
    respond_with(@user_profile)
  end

  def update
    @user_profile.update(user_profile_params)
    respond_with(@user_profile)
  end

  def destroy
    @user_profile.destroy
    respond_with(@user_profile)
  end

  private
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    def user_profile_params
      params.require(:user_profile).permit(:first_name, :second_name, :address_1, :adddress_2, :city, :county, :postcode, :country_id, :telephone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
 def options_from_collection_for_select_with_attributes(collection, value_method, text_method, attr_name, attr_field, selected = nil)
  options = collection.map do |element|
    [element.send(text_method), element.send(value_method), attr_name => element.send(attr_field)]
  end
  selected, disabled = extract_selected_and_disabled(selected)
  select_deselect = {}
  select_deselect[:selected] = extract_values_from_collection(collection, value_method, selected)
  select_deselect[:disabled] = extract_values_from_collection(collection, value_method, disabled)

  options_for_select(options, select_deselect)
 end
end

app/helpers/event_images_helper.rb
module EventImagesHelper
end

app/helpers/event_times_helper.rb
module EventTimesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.slim
= simple_form_for(@user_profile) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :second_name
    = f.input :address_1
    = f.input :adddress_2
    = f.input :city
    = f.input :county
    = f.input :postcode
    = f.input :country_id
    = f.input :telephone
    = f.input :email

  .form-actions
    = f.button :submit

app/views/user_profiles/edit.html.slim
h1 Editing user_profile

== render 'form'

= link_to 'Show', @user_profile
'|
= link_to 'Back', user_profiles_path

app/views/user_profiles/index.html.slim
h1 Listing user_profiles

table
  thead
    tr
      th First name
      th Second name
      th Address 1
      th Adddress 2
      th City
      th County
      th Postcode
      th Country
      th Telephone
      th Email
      th
      th
      th

  tbody
    - @user_profiles.each do |user_profile|
      tr
        td = user_profile.first_name
        td = user_profile.second_name
        td = user_profile.address_1
        td = user_profile.adddress_2
        td = user_profile.city
        td = user_profile.county
        td = user_profile.postcode
        td = user_profile.country_id
        td = user_profile.telephone
        td = user_profile.email
        td = link_to 'Show', user_profile
        td = link_to 'Edit', edit_user_profile_path(user_profile)
        td = link_to 'Destroy', user_profile, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User profile', new_user_profile_path

app/views/user_profiles/new.html.slim
h1 New user_profile

== render 'form'

= link_to 'Back', user_profiles_path

app/views/user_profiles/show.html.slim
p#notice = notice

p
  strong First name:
  = @user_profile.first_name
p
  strong Second name:
  = @user_profile.second_name
p
  strong Address 1:
  = @user_profile.address_1
p
  strong Adddress 2:
  = @user_profile.adddress_2
p
  strong City:
  = @user_profile.city
p
  strong County:
  = @user_profile.county
p
  strong Postcode:
  = @user_profile.postcode
p
  strong Country:
  = @user_profile.country_id
p
  strong Telephone:
  = @user_profile.telephone
p
  strong Email:
  = @user_profile.email

= link_to 'Edit', edit_user_profile_path(@user_profile)
'|
= link_to 'Back', user_profiles_path