config/routes.rb
Rails.application.routes.draw do
  resources :event_images

  mount Ckeditor::Engine => '/ckeditor'
  resources :user_profiles

  resources :locations

  resources :exercises

  resources :event_times

  resources :events
  
  resources :user_event_times

  devise_for :users

  root 'event_times#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
        user ||= User.new # guest user (not logged in)
        if user.admin?
          can :manage, :all
        else
          can :read, :all
        end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_times
  validates_presence_of :name,:description
end

app/models/event_image.rb
class EventImage < ActiveRecord::Base
  has_attached_file :event_image_thumb, :styles => { }, :default_url => "/images/:style/missing.png"
  has_attached_file :event_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :event_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :event_image_thumb, :content_type => /\Aimage\/.*\Z/
  has_many :event_times, through: :event_time_images
end

app/models/event_time.rb
class EventTime < ActiveRecord::Base
  belongs_to :event, :foreign_key => "event_id"
  has_many :location_events
  has_many :locations, through: :location_events
  has_many :event_time_images
  has_many :event_images, through: :event_time_images
  has_many :exercise_events, :dependent => :destroy
  has_many :exercises, through: :exercise_events
  has_many :user_event_times
  has_many :users, through: :user_event_times
  
  accepts_nested_attributes_for :event
  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :exercise_events,:reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
end

app/models/event_time_image.rb
class EventTimeImage < ActiveRecord::Base
  belongs_to :event_time
  belongs_to :event_images
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :exercise_events
  has_many :event_times, through: :excercise_events
end

app/models/exercise_event.rb
class ExerciseEvent < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :event_time
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :location_events
  has_many :event_times ,through: :location_events
end

app/models/location_event.rb
class LocationEvent < ActiveRecord::Base
  belongs_to :locations
  belongs_to :event_times
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :user_event_times
  has_many :event_times, through: :user_event_times
end

app/models/user_event_time.rb
class UserEventTime < ActiveRecord::Base
  belongs_to :users
  belongs_to :event_time
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
end

app/controllers/event_images_controller.rb
class EventImagesController < ApplicationController
  before_action :set_event_image, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    @event_images = EventImage.all
    respond_with(@event_images)
  end

  def show
    respond_with(@event_image)
  end

  def new
    
    @event_image = EventImage.new
    
    respond_to do |format|
      format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
      format.js
    end
  end

  def edit
  end

  def create
    puts 'hello'
    @event_image = EventImage.new(event_image_params)
    if @event_image.save
    #passed  
    else
    #errors
    @event_image.errors.full_messages
   
    end
    
  end

  def update
    @event_image.update(event_image_params)
    respond_with(@event_image)
  end

  def destroy
    @event_image.destroy
    respond_with(@event_image)
  end

  private
    def set_event_image
      @event_image = EventImage.find(params[:id])
    end

    def event_image_params
      params.require(:event_image).permit(:alt_text, :description, :event_image, :event_image_thumb)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    
    @event = Event.new
    respond_to do |format|
      format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
      format.js
    end
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
    #passed  
    else
    #errors
    @event.errors.full_messages
   
    end
    respond_to do |format|
        format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
        format.js
      end  
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description)
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  
  def index
    @exercises = Exercise.all
    respond_with(@exercises)
  end

  def show
    respond_with(@exercise)
  end

  def new
    @exercise = Exercise.new
    respond_to do |format|
      format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
      format.js
    end
  end

  def edit
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
    #passed  
    else
    #errors
    @exercise.errors.full_messages
   
    end
    respond_to do |format|
        format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
        format.js
      end  
  end

  def update
    @exercise.update(exercise_params)
    respond_with(@exercise)
  end

  def destroy
    @exercise.destroy
    respond_with(@exercise)
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
 def options_from_collection_for_select_with_attributes(collection, value_method, text_method, attr_name, attr_field, selected = nil)
  options = collection.map do |element|
    [element.send(text_method), element.send(value_method), attr_name => element.send(attr_field)]
  end
  selected, disabled = extract_selected_and_disabled(selected)
  select_deselect = {}
  select_deselect[:selected] = extract_values_from_collection(collection, value_method, selected)
  select_deselect[:disabled] = extract_values_from_collection(collection, value_method, disabled)

  options_for_select(options, select_deselect)
 end
end

app/helpers/event_images_helper.rb
module EventImagesHelper
end

app/helpers/event_times_helper.rb
module EventTimesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/event_images/_form.html.slim
ul.errors
= simple_form_for(@event_image , :remote => true , html: {multipart: true}  ) do |f|
  = f.error_notification
  = form_authenticity_token
  .form-inputs
    .row
      .form-group
        = f.label :alt_text, class: "col-sm-2 control-label"
        .col-sm-6
          = f.input_field :alt_text, class: "form-control"
	.row
      .form-group
        = f.label :description, class: "col-sm-2 control-label"
        .col-sm-6
          = f.input_field :description, class: "form-control"	
	.row
      .form-group
        = f.label :event_image_thumb, class: "col-sm-2 control-label"
        .col-sm-6
          = f.input_field :event_image_thumb, class: "form-control"	
	.row
      .form-group
        = f.label :event_image, class: "col-sm-2 control-label"
        .col-sm-6
          = f.input_field :event_image, class: "form-control"	
    .row
      .form-group
        .col-sm-offset-2.col-sm-6
          = f.submit "Submit", class: "btn btn-primary"

app/views/event_images/_new.html.slim
h1 New event_image

== render 'form'

= link_to 'Back', event_images_path

app/views/event_images/create.js.erb
$("ul.errors").html("")
<% if @event_image.errors.any? %>
  <% @event_image.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li/>").html("<%= message.html_safe %>"))
  <% end %>
<% else %> 
  $("#event_time_exercise_time_image_event_id").append('<option value="<%= @event_image.id %>" data-img-src="<%= @event_image.event_image %>"><%= @event_image.alt_text %></option>');
  $('[id=event_time_exercise_time_image_event_id]').val( "<%= @event_image.id %>" )
  $("#ajax-modal").modal('hide')
  $('select').imagepicker();
<% end %>

app/views/event_images/edit.html.slim
h1 Editing event_image

== render 'form'

= link_to 'Show', @event_image
'|
= link_to 'Back', event_images_path

app/views/event_images/index.html.slim
h1 Listing event_images

table
  thead
    tr
      th Alt text
      th Description
      th Event image
      th Event image Thumb
      th
      th
      th

  tbody
    - @event_images.each do |event_image|
      tr
        td = event_image.alt_text
        td = event_image.description
        td = event_image.event_image
        td = event_image.event_image_thumb
        td = link_to 'Show', event_image
        td = link_to 'Edit', edit_event_image_path(event_image)
        td = link_to 'Destroy', event_image, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Event image', new_event_image_path

app/views/event_images/new.js.erb
$(".modal-body-content").html("<%= escape_javascript(render 'event_images/new')  %>");

app/views/event_images/show.html.slim
p#notice = notice

p
  strong Alt text:
  = @event_image.alt_text
p
  strong Description:
  = @event_image.description
p
  strong Event image:
  = @event_image.event_image

= link_to 'Edit', edit_event_image_path(@event_image)
'|
= link_to 'Back', event_images_path